# Generated by Django 3.0.4 on 2021-02-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastLogout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=180)),
                ('last_logout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=180)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, default=5, max_digits=9)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, default=5, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('username', models.CharField(max_length=180)),
            ],
        ),
    ]
